[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_model"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[prune]
  unused-packages = true
  go-tests = true

  [[prune.project]]
    name = "github.com/ethereum/go-ethereum"
    unused-packages = false